### ISSUE TITLE
How to add/remove components at run-time?

### ISSUE THREAD

**Issue by caracal7** [colejd/guify#1]
And how to disable components? For example buttons...

**Comment by colejd** [comment]
Sorry for the delay! To add new components at runtime, have a look at the usage of `Register()` in [the example page](https://github.com/colejd/guify/blob/47984b1e32a2bbc719501ae7fe0b4586e322d3dd/example/index.html#L79).

I never really gave any thought to removing components. I just came up with a quick implementation that I'll be pushing soon, along with the ability to enable / disable components.

**Comment by caracal7** [comment]
Thanks for answer)
One more useful thing is ability to change properties of the components at runtime. For example range min/max or any captions.

**Comment by caracal7** [comment]
Maybe now is possible to complete destroy guify instance and recreate it with another configuration?

**Comment by zadvorsky** [comment]
Could you publish this change to NPM?

**Comment by colejd** [comment]
Well, it's a bit late, but... I've published the change. You can find it starting in version 0.13.1.
