### ISSUE TITLE
React version

### ISSUE THREAD

**Issue by dbismut** [colejd/guify#5]
Hey! I loved your lib and decided to create a thin React wrapper around it.

https://github.com/dbismut/react-guify

Maybe you’d like to mention it in the ReadMe?

Also, I may have overlooked some options but there’s no way to update panel or component options after initialization, is there?

**Comment by colejd** [comment]
Oh wow, thank you! I’ll add that when I’m able. 

There is also no way to do that at the moment. I’d like to do a rewrite, but I don’t really have the time — if you decide to submit a PR, though, I’ll merge it!
